### ISSUE TITLE
Emacs 26.1: Lisp nesting exceeds ‘max-lisp-eval-depth’

### ISSUE THREAD

**Issue by timn** [clips-mode/clips-mode#20]
There seem to have been changes for Emacs 26.1 that break clips-mode. For example, when opening
https://github.com/fawkesrobotics/fawkes/blob/timn/cx-subgoals/src/plugins/clips-executive/clips/goal.clp, when adding to a comment I get:

    Lisp nesting exceeds ‘max-lisp-eval-depth’

When adding

    (setq max-lisp-eval-depth 10000)

the next issue the is:

    Variable binding depth exceeds max-specpdl-size

I suspect it is due to some changes in Emacs 26.1 since it was working fine before. Any idea?

**Comment by grettke** [comment]
When the code runs on Emacs 26.1, Emacs is running out of memory. 

As you shared, even when you bump up the memory, it still runs out of memory, it just takes longer.

Triage for this to make sure you can keep moving forward: can you use Emacs <26.1 for now?

Next step is for us to make an minimum example of reproducing this issue. Can you pare down your code to the simplest thing possible that triggers this error?

Have you tried debugging the error to get more details? That would help us make a reproducible issue. You can call `toggle-debug-on-error to turn that on.

Are you up for taking this task?

Otherwise I will assign it to myself. Whatever makes sense for you.

**Comment by timn** [comment]
@grettke, thanks for the quick reply. With increasing the eval depth I got rid of the most urgent problem: after each character the cursor would go to the first column. The second error shows up, but has no obvious consequences. I'm actually very happy with Emacs 26.1, it now automatically adapts formatting colors depending on the terminal background, so no, I don't plan on going back ;-)

The code link I gave is already pretty simply. Just try to edit any of the comments in the file and you spot the issue right away.

Currently I cannot give this more time a this time, sorry. I'd be happy to test updates though and give feedback.
